# This is a basic workflow to help you get started with Actions

#name: Auto Merge Dependabot

# Controls when the action will run. 
name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.App }}"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.App}}
#on:
#  pull_request_target:
#    types: [opened]
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
  # This workflow contains a single job called "build"
#  update:
    # The type of runner that the job will run on
#    runs-on: ubuntu-latest
#    if: github.actor == 'dependabot[bot]'
#    steps:
#      - name: Run a multi-line script
#        run: |
#          curl \
#            -X PUT \
#            -u MBS9Admin:${{ secrets.App }} \
#            -H "Accept: application/vnd.github.v3+json" \
#            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.number }}/merge \
#            -d '{"commit_title":"auto"}'
